name: "Transmute"

description: |
  The Transmute GitHub Action

inputs:
  transmute:
    description: |
      The transmute command to run.
  neo4j-uri:
    description: |
      Neo4j Connection URL.
    require: false
  neo4j-user:
    description: |
      Neo4j User.
    require: false
  neo4j-password:
    description: |
      Neo4j Password.
    require: false
  transmute-client-id:
    description: |
      OAuth2 Client ID.
    require: false
  transmute-client-secret:
    description: |
      OAuth2 Client Secret.
    require: false
  transmute-api:
    description: |
      Resource Owner API.
    require: false
  azure-tenant-id:
    description: |
      AZURE_TENANT_ID as described in https://github.com/Azure/azure-sdk-for-js.
    require: false
  azure-client-id:
    description: |
      AZURE_CLIENT_ID as described in https://github.com/Azure/azure-sdk-for-js.
    require: false
  azure-client-secret:
    description: |
      AZURE_CLIENT_SECRET as described in https://github.com/Azure/azure-sdk-for-js.
    require: false
  azure-kid:
    description: |
      AZURE_KEY_ID as described in https://github.com/Azure/azure-sdk-for-js.
      For example: https://<account>.vault.azure.net/keys/<key-name>/5d...a0
    require: false
  gcp-sa-email:
    description: |
      Google Cloud Platform Service Account Email
    require: false
  gcp-sa-private-key:
    description: |
      Google Cloud Platform Service Account Private Key
    require: false
  gcp-kms-key-name:
    description: |
      Google Cloud Platform Cloud KMS Key Name
    require: false

outputs:
  yaml:
    description: "The output as yaml."
  json:
    description: "The output as json."
  cbor:
    description: "The output as cbor."
  jws:
    description: "The output as compact jws."
  jwe:
    description: "The output as compact jwe."
  jwt:
    description: "The output as compact jwt."
  sd-jwt:
    description: "The output as compact sd-jwt."

runs:
  using: "node20"
  main: "dist/index.js"
