name: "Transmute"

description: |
  The Transmute GitHub Action

inputs:
  transmute:
    description: |
      The transmute command to run.

outputs:
  json:
    description: "The output as json."
  cbor:
    description: "The output as cbor."
  jws:
    description: "The output as compact jws."

runs:
  using: "node20"
  main: "dist/index.js"
