name: "Transmute"

description: |
  The Transmute GitHub Action

inputs:
  transmute:
    description: |
      The transmute command to run.
  neo4j-uri:
    description: |
      Neo4j Connection URL.
    require: false
  neo4j-user:
    description: |
      Neo4j User.
    require: false
  neo4j-password:
    description: |
      Neo4j Password.
    require: false

outputs:
  yaml:
    description: "The output as yaml."
  json:
    description: "The output as json."
  cbor:
    description: "The output as cbor."
  jws:
    description: "The output as compact jws."
  jwe:
    description: "The output as compact jwe."
  jwt:
    description: "The output as compact jwt."
  sd-jwt:
    description: "The output as compact sd-jwt."

runs:
  using: "node20"
  main: "dist/index.js"
