#!/bin/bash
# Installs minikube, kubectl, and transmute into a minikube cluster
: ${TRANSMUTE_RELEASE:='master'}
: ${TRANSMUTE_DIR:=$HOME/.transmute}
: ${TRANSMUTE_BIN:=$TRANSMUTE_DIR/bin}
: ${TRANSMUTE_REPO:=$TRANSMUTE_DIR/git/transmute}
: ${VERBOSITY:=10}
: ${HELM_INSTALL_DIR:=$TRANSMUTE_BIN}
: ${MY_KUBE_VERSION:=v1.9.6}
: ${FIX_DOTFILES:="true"}
: ${NVM_DIR_ADDS:="true"}
: ${NVM_VERSION:='0.33.9'}
: ${USE_WARN:=y}

export CWD=$(pwd)
export PATH=$TRANSMUTE_BIN:$PATH

squawk () {
  # This function simplifies error reporting and verbosity
  # call it by preceding your message with a verbosity level
  # e.g. `squawk 3 "This is a squawk"`
  # if the current verbosity level is greater than or equal to
  # the number given then this function will echo out your message
  # and pad it with # to let you now how verbose that message was
  squawk_lvl=$1
  shift
  squawk=$1
  shift
  squawk_opt=$@

  if [[ "$VERBOSITY" -ge "$squawk_lvl" ]] ; then
  count_squawk=0
    while [[ "$count_squawk" -lt "$squawk_lvl" ]]; do
      printf "#"
      count_squawk=`expr $count_squawk + 1`
    done
    echo " $squawk"
  fi
}

# Check for config env file
if [ -e $TRANSMUTE_DIR/env ]; then
  source $TRANSMUTE_DIR/env
  if [ $VERBOSITY -gt '0' ]; then
    ls -al $TRANSMUTE_DIR/env
    env file found and sourced
  fi
fi

errror () {
  echo "-------------------------------------------------------------"
  echo -e "\n \n  "
  echo "ERROR!!!  --  "
}

# Check if a command exists
check_cmd () {
  if ! type "$1" > /dev/null; then
    errror
    echo "$1 was not found in your path!"
    echo "To proceed please install $1 to your path and try again!"
    exit 1
  fi
}

warrrn () {
  sleep 1
  printf "(ctrl-c now to stop if this is not what you intend)!"
  sleep 1; printf "!"; sleep 1; printf "!"
  sleep 1; printf "!"
  sleep 1; echo "!"
  sleep 1; echo "--"
  sleep 1
}

chkdir () {
  if [ ! -w $1 ] ; then
    sudo mkdir -p $1
    sudo chown $USER $1
  fi
  if [ ! -w $1 ] ; then
    errror
    echo "Cannot write to $1, please check your permissions"
    exit 2
  fi
}

# these vars are used by the following functions
LINE_TO_ADD=''
TARGET_FILE_FOR_ADD=~/.profile

check_if_line_exists()
{
  squawk 3 "Checking for '$LINE_TO_ADD'  in $TARGET_FILE_FOR_ADD"
  grep -qsFx "$LINE_TO_ADD" $TARGET_FILE_FOR_ADD
}

add_line_to()
{
  squawk 3 "Adding '$LINE_TO_ADD'  to $TARGET_FILE_FOR_ADD"
  TARGET_FILE=$TARGET_FILE_FOR_ADD
    [ -w "$TARGET_FILE" ] || TARGET_FILE=$TARGET_FILE_FOR_ADD
    printf "%s\n" "$LINE_TO_ADD" >> "$TARGET_FILE"
}

macminikube () {
	squawk 3 'Installing minikube'
	brew cask install minikube
}

mackubectl () {
	squawk 3 'Installing kubectl'
	brew install kubectl
}

install_mac_virtualbox () {
  squawk 3 'Installing virtualbox'
	brew cask install virtualbox
}

machelm () {
	squawk 3 'Installing helm'
	brew install kubernetes-helm
}

macnsenter () {
	squawk 3 'NOT Installing nsenter'
	#brew install kubernetes-nsenter
}


macreadlink () {
	squawk 3 'Installing coreutils'
	#Installs 'greadlink' tool
	brew install coreutils
}

windowsminikube () {
	squawk 3 'Installing minikube'
	choco install minikube
}

windowskubectl () {
	squawk 3 'Installing kubectl'
	choco install kubernetes-cli
}

windowshelm () {
	squawk 3 'Installing helm'
	choco install helm
}

windowsnsenter () {
	squawk 3 'Installing nsenter'
	choco install nsenter
}

install_kubectl_linux () {
  if ! type "kubectl" >/dev/null 2>/dev/null; then
    squawk 3 'Installing kubectl'
    TMP=$(mktemp -d --suffix=KUBECTLTMP)
    cd $TMP
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$MY_KUBE_VERSION/bin/linux/amd64/kubectl
    chmod +x kubectl
    sudo mv -v kubectl $TRANSMUTE_BIN
    cd
    rmdir $TMP
  fi
}

install_minikube_linux () {
  if ! type "minikube" >/dev/null 2>/dev/null; then
    squawk 3 'Installing minikube'
    TMP=$(mktemp -d --suffix=MINIKUBETMP)
    mkdir -p $HOME/.kube || true
    touch $HOME/.kube/config
    cd $TMP
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube $TRANSMUTE_BIN/
    cd
    rmdir $TMP
  fi
}

install_helm_linux () {
  if ! type "helm" >/dev/null 2>/dev/null; then
    TMP=$(mktemp -d --suffix=HELMTMP)
    cd $TMP
    squawk 3 'Getting helmget'
    curl -Lo $TMP/helmget https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    HELM_INSTALL_DIR=$HELM_INSTALL_DIR
    squawk 3 'Installing helm'
    sudo -E bash -l $TMP/helmget
    rm $TMP/helmget
    cd
    rmdir $TMP
  fi
}

nvm_dir_adds () {
  LINE_TO_ADD='export NVM_DIR=~/.nvm'
  TARGET_FILE_FOR_ADD=~/.zshrc
  check_if_line_exists || add_line_to
  TARGET_FILE_FOR_ADD=~/.bash_profile
  check_if_line_exists || add_line_to

  LINE_TO_ADD='source ~/.nvm/nvm.sh'
  TARGET_FILE_FOR_ADD=~/.zshrc
  check_if_line_exists || add_line_to
  TARGET_FILE_FOR_ADD=~/.bash_profile
  check_if_line_exists || add_line_to
}

dotfiles_install () {
  if [[ $VERBOSITY -gt '1' ]]; then
    squawk 3 'Adjusting dotfiles'
  fi
  touch $HOME/.zshrc
  touch $HOME/.bashrc
  # here we'll make a bin dir in $HOME and add it to path
  chkdir $TRANSMUTE_BIN
  LINE_TO_ADD="$(printf "export PATH=%s:\$PATH" $TRANSMUTE_BIN)"
  TARGET_FILE_FOR_ADD=$HOME/.bashrc
  check_if_line_exists || add_line_to
  TARGET_FILE_FOR_ADD=$HOME/.zshrc
  check_if_line_exists || add_line_to
}

install_certbot () {
  if ! type "certbot-auto" >/dev/null 2>/dev/null; then
    TMP=$(mktemp -d)
    cd $TMP
    wget https://dl.eff.org/certbot-auto
    chmod a+x ./certbot-auto
    wget -N https://dl.eff.org/certbot-auto.asc
    if type "gpg2" >/dev/null 2>/dev/null; then
      set +e
      gpg2 --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      gpg2 --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      set -e
      gpg2 --trusted-key 4D17C995CD9775F2 --verify certbot-auto.asc certbot-auto
    elif type "gpg" >/dev/null 2>/dev/null; then
      set +e
      gpg --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --verbose --recv-key A2CFB51FA275A7286234E7B24D17C995CD9775F2
      set -e
      gpg --trusted-key 4D17C995CD9775F2 --verify certbot-auto.asc certbot-auto
    else
      echo 'gpg not found'
    fi
    rm certbot-auto.asc
    sudo chmod +x certbot-auto
    sudo mv certbot-auto $TRANSMUTE_BIN/
    set +e
    certbot-auto
    set -e
    cd
    rm -Rf $TMP
  else
    squawk 3 'certbot-auto already installed skipping'
  fi
}

install_nvm () {
  squawk 5 "install_nvm"
  set +e
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  # test if nvm is present if not, throw away the error
  this_output=$(nvm  --version 2>/dev/null)
  set -e

  if [ "$this_output" = "$NVM_VERSION" ]; then
    squawk 3 "NVM $NVM_VERSION is already installed skipping"
  else
    touch ~/.profile

    set +e
    mkdir $HOME/.nvm
    curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v$NVM_VERSION/install.sh | bash
    set -e

    if [ "$NVM_DIR_ADDS" = "true" ]; then
      nvm_dir_adds
    fi
  fi
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

announce_prefix_fail () {
  echo "failed to write to the npm prefix directory, you should set your npm prefix to a directory you can write to"
  echo "The following documentation details this procedure: https://docs.npmjs.com/getting-started/fixing-npm-permissions"
}

check_prefix_npm () {

  trap announce_prefix_fail EXIT
  TMP_FILE=$(mktemp $(npm config get prefix)/tmp.XXXXXXXXXX)
  if [ "$?" -ne 0 ]; then
    announce_prefix_fail
  else
    rm $TMP_FILE
  fi
  trap - EXIT
}

install_lerna_npm () {
  if ! type "lerna" >/dev/null 2>/dev/null; then
    npm i -g lerna@2.9.0
  else
    squawk 3 'lerna already installed skipping'
  fi
}

install_truffle_npm () {
  if ! type "truffle" >/dev/null 2>/dev/null; then
    npm i -g truffle@4.1.7
  else
    squawk 3 'truffle already installed skipping'
  fi
}

install_ngrok_npm () {
  if ! type "ngrok" >/dev/null 2>/dev/null; then
    npm i -g ngrok
  else
    squawk 3 'ngrok already installed skipping'
  fi
}

lts_install () {
  if ! type "npm" >/dev/null 2>/dev/null; then
    if [[ $VERBOSITY -gt '2' ]]; then
      squawk 3 'Installing Node 8 LTS/carbon'
    fi

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    set +e
    nvm ls-remote --lts=carbon
    if [[ $VERBOSITY -gt '2' ]]; then
      squawk 3 "Engage nvm to install lts/carbon"
    fi
    nvm install --lts=carbon
    if [[ $VERBOSITY -gt '2' ]]; then
      squawk 3 "Engage nvm to alias lts/carbon to default"
    fi
    nvm alias default lts/carbon
    set -e
  else
      squawk 3 'npm already installed skipping'
  fi
}

install_socat () {
  if ! type "socat" >/dev/null 2>/dev/null; then
    if type "apt-get" >/dev/null 2>/dev/null; then
      sudo apt-get install -y socat
    elif type "dnf" >/dev/null 2>/dev/null; then
      sudo dnf install -y socat
    elif type "zypper" >/dev/null 2>/dev/null; then
      sudo zypper --non-interactive install -y socat
    elif type "pacman" >/dev/null 2>/dev/null; then
      sudo pacman -Sy --noconfirm socat
    elif type "brew" >/dev/null 2>/dev/null; then
      brew install socat < /dev/null
    elif type "chocolatey" >/dev/null 2>/dev/null; then
      chocolatey install socat
    else
      echo 'No appropriate installer found for socat, install socat and run this script again'
      exit 1
    fi
  else
    squawk 3 'socat already installed skipping'
  fi
}

install_curl () {
  if ! type "curl" >/dev/null 2>/dev/null; then
    if type "apt-get" >/dev/null 2>/dev/null; then
      sudo apt-get install -y curl
    elif type "dnf" >/dev/null 2>/dev/null; then
      sudo dnf install -y curl
    elif type "zypper" >/dev/null 2>/dev/null; then
      sudo zypper --non-interactive install -y curl
    elif type "pacman" >/dev/null 2>/dev/null; then
      sudo pacman -Sy --noconfirm curl
    elif type "brew" >/dev/null 2>/dev/null; then
      brew install curl < /dev/null
    elif type "chocolatey" >/dev/null 2>/dev/null; then
      chocolatey install curl
    else
      echo 'No appropriate installer found for curl, install curl and run this script again'
      exit 1
    fi
  else
    squawk 3 'curl already installed skipping'
  fi
}

install_git () {
  if ! type "git" >/dev/null 2>/dev/null; then
    if type "apt-get" >/dev/null 2>/dev/null; then
      sudo apt-get install -y git
    elif type "dnf" >/dev/null 2>/dev/null; then
      sudo dnf install -y git
    elif type "zypper" >/dev/null 2>/dev/null; then
      sudo zypper --non-interactive install -y git
    elif type "pacman" >/dev/null 2>/dev/null; then
      sudo pacman -Sy --noconfirm git
    elif type "brew" >/dev/null 2>/dev/null; then
      brew install git < /dev/null
    elif type "chocolatey" >/dev/null 2>/dev/null; then
      chocolatey install git
    else
      echo 'No appropriate installer found for git, install git and run this script again'
      exit 1
    fi
  else
    squawk 3 'git already installed skipping'
  fi
}

install_jq () {
  if ! type "jq" >/dev/null 2>/dev/null; then
    if type "apt-get" >/dev/null 2>/dev/null; then
      sudo apt-get install -y jq
    elif type "dnf" >/dev/null 2>/dev/null; then
      sudo dnf install -y jq
    elif type "zypper" >/dev/null 2>/dev/null; then
      sudo zypper --non-interactive install -y jq
    elif type "pacman" >/dev/null 2>/dev/null; then
      sudo pacman -Sy --noconfirm jq
    elif type "brew" >/dev/null 2>/dev/null; then
      brew install jq < /dev/null
    elif type "chocolatey" >/dev/null 2>/dev/null; then
      chocolatey install jq
    else
      echo 'No appropriate installer found for jq, install jq and run this script again'
      exit 1
    fi
  else
    squawk 3 'jq already installed skipping'
  fi
}

transmute-cli_install () {
  cd $TRANSMUTE_REPO/packages/transmute-cli
  npm i
  npm run build
  npm i -g
}

windowsreqs () {
  check_cmd chocolatey
  install_curl
  install_git
  install_socat
  windowskubectl
  windowsminikube
  windowshelm
  windowsnsenter
  install_nvm
  lts_install
  check_prefix_npm
  install_ngrok_npm
  install_truffle_npm
  install_lerna_npm
  install_certbot
  install_jq
  dotfiles_install
  transmute-cli_install
}

macreqs () {
  check_cmd brew
  install_curl
  install_git
  install_socat
  set +e
  brew install gnupg < /dev/null
  set -e
  install_mac_virtualbox
  mackubectl
  macminikube
  machelm
  macnsenter
  macreadlink
  install_nvm
  lts_install
  check_prefix_npm
  install_ngrok_npm
  install_truffle_npm
  install_lerna_npm
  install_certbot
  install_jq
  dotfiles_install
  transmute-cli_install
}

linuxreqs () {
  #linuxreqs: $(TRANSMUTE_BIN) run_dotfiles minikube kubectl helm nsenter
  install_curl
  install_git
  install_socat
  install_kubectl_linux
  install_minikube_linux
  install_helm_linux
  install_nvm
  lts_install
  check_prefix_npm
  install_ngrok_npm
  install_truffle_npm
  install_lerna_npm
  install_certbot
  install_jq
  dotfiles_install
  transmute-cli_install
}

initializer () {
  ls  $TRANSMUTE_DIR/git
  ls $TRANSMUTE_DIR/git/transmute
  set +e
  cd $TRANSMUTE_DIR/git/transmute/transmute-config
  set -e
  cp .example.env .env
  set +e
  cd $TRANSMUTE_DIR/git/transmute
  set -e
  npm i
  set +e
  cd $CWD
  set -e
}

run_it () {
set -e
#set -u

# Let's display everything on stderr.
exec 1>&2

UNAME=$(uname)
if [ "$UNAME" = "Linux" -o "$UNAME" = "Darwin" ] ; then
  squawk 3 " $UNAME is a Supported OS"
elif [ "$UNAME" ">" "MINGW" -a "$UNAME" "<" "MINGX" ] ; then
  echo " $UNAME is not a Supported OS"
  exit 1
else
  echo " $UNAME is not a Supported OS"
  echo "Sorry, this OS is not supported yet via this installer."
  exit 1
fi

if [ "$UNAME" = "Darwin" ] ; then
  check_cmd brew
  ### OSX ###
  squawk 3 'Checking arch'
  if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
    # Can't just test uname -m = x86_64, because Snow Leopard can
    # return other values.
    echo "Only 64-bit Intel processors are supported at this time in OSX."
    exit 1
  fi

  PLATFORM="os.osx.x86_64"
elif [ "$UNAME" = "Linux" ] ; then
  ### Linux ###
  LINUX_ARCH=$(uname -m)
  if [ "${LINUX_ARCH}" = "x86_64" ] ; then
    PLATFORM="os.linux.x86_64"
  else
    echo "Unusable architecture: ${LINUX_ARCH}"
    echo "transmute only supports x86_64 for now."
    exit 1
  fi
elif [ "$UNAME" = "CYGWIN_NT-10.0" ] ; then
  PLATFORM="os.cygwin.x86_64"
fi

echo "Warning!"
sleep 1
echo "This script will install minikube, kubectl and helm,
and then install transmute."
if [[ "$USE_WARN" == 'y' ]]; then
  warrrn
fi

squawk 3 "Checking $TRANSMUTE_DIR"
mkdir -p $TRANSMUTE_DIR/git
mkdir -p $TRANSMUTE_BIN

if [ -e "$TRANSMUTE_DIR/git" ]; then
  squawk 3 "$TRANSMUTE_DIR/git exists already, proceeding"
else
  squawk 3 "$TRANSMUTE_DIR/git does not exist already, proceeding"
  cd $TRANSMUTE_DIR
  mkdir -p $TRANSMUTE_DIR/git
fi

# Install transmute components into k8s
# Grab the transmute dir
# Note in CI this has already been symlinked and does not run there
# however this will
if [ "$TRAVIS" = 'true' ]; then
  echo 'travis ci skipping git actions'
elif [ -e "$TRANSMUTE_REPO" ]; then
  squawk 3 "$TRANSMUTE_REPO exists already, proceeding"
  squawk 3 'Updating the transmute repo'
  cd $TRANSMUTE_REPO
  git fetch --tags
  git checkout $TRANSMUTE_RELEASE
  git submodule update --init
  cd $CWD
else
  cd $TRANSMUTE_DIR/git
  ls -alh
  squawk 3 'Cloning the latest transmute repo'
  git clone --depth=1 \
   https://github.com/transmute-industries/transmute.git
  cd $TRANSMUTE_REPO
  git fetch --tags
  git checkout $TRANSMUTE_RELEASE
  git submodule update --init
  cd $CWD
fi

if [ "$FIX_DOTFILES" = "true" ]; then
  dotfiles_install
fi

squawk 5 ' make reqs'
if [ "$PLATFORM" = "os.linux.x86_64" ] ; then
  linuxreqs
elif [ "$PLATFORM" = "os.osx.x86_64" ] ; then
  macreqs
elif [ "$PLATFORM" = "os.windows.x86_64" ] ; then
  windowsreqs
fi

squawk 3 'check helm'
check_cmd helm
squawk 3 'check kubectl'
check_cmd kubectl
squawk 3 'check minikube'
check_cmd minikube
#check_cmd nsenter

squawk 3 'Initializer'
initializer

echo 'The bootstrap has finished'
echo 'you have completed all the way to "npm run setup" here:'
echo 'https://github.com/transmute-industries/transmute#environment-scripts-and-updating'
if [ "$PLATFORM" = "os.osx.x86_64" ] ; then
  SETUP_DIR=$(greadlink -f $TRANSMUTE_DIR)
else
  SETUP_DIR=$(readlink -f $TRANSMUTE_DIR)
fi
echo "First you will need to source your ~/.bashrc or ~/.zshrc file"
echo "Then you should be able run 'npm run setup' inside '$SETUP_DIR'"

trap - EXIT
# End run it wrapper
}

check_cmd mktemp
check_cmd uname

run_it
