export const USER_REGISTERD = "USER_REGISTERD";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_STATUS_CHANGE = "USER_STATUS_CHANGE";
export const USER_DATA_RECEIVED = "USER_DATA_RECEIVED";
