#!/bin/sh
: ${HELM_VERSION:='v2.8.2'}
: ${HELM_PREFIX:="$HOME/.local/bin"}
: ${HELM_URL:="https://storage.googleapis.com/kubernetes-helm/helm-$HELM_VERSION-linux-amd64.tar.gz"}

TMP=$(mktemp -d)
cleanup_tmp () {
  rm -Rf $TMP
}
trap cleanup_tmp EXIT
cd $TMP

echo "Installing $HELM_VERSION"
curl -sL $HELM_URL -o helm.tgz
echo $TMP
/bin/bash
tar zxvf helm.tgz

cd linux-amd64
chmod +x helm
sudo mv helm $HELM_PREFIX/helm
