#!/bin/bash -l
export PATH=$HOME/.transmute/bin:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
helm init --force-upgrade --tiller-image powerhome/tiller:git-3b22ecd
w8s/kube-dns.w8
w8s/tiller.w8

node -v
npm -v

npm install -g codecov lerna@2.9.0 truffle@4.1.3

lerna -v
truffle version

w8s/kubectl.w8
kubectl cluster-info
nsenter --version
minikube addons enable ingress

helm install stable/kong --name gateway
helm install stable/ipfs --name decentralized-storage

