#!/bin/bash -l
export PATH=$HOME/.transmute/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

w8s/kubectl.w8
w8s/kube-dns.w8
kubectl create -f ./tiller/rbac-tiller-config.yaml
#helm init --force-upgrade --tiller-image powerhome/tiller:git-3b22ecd
helm init --upgrade
kubectl run nginx --image=nginx:alpine
w8s/tiller.w8
ls -lh ~/.kube/config
sleep 10
kubectl get pods -n kube-system
kubectl get nodes
kubectl get pods
#export KUBECONFIG=$HOME/.kube/config
#KUBECONFIG=$HOME/.kube/config \
#echo "do helm install with $KUBECONFIG"
#kubectl get nodes
#w8s/generic.w8 nginx default
which nsenter
helm version --debug
helm install stable/kong --name gateway
helm install stable/ipfs --name decentralized-storage
helm install ./components/ganache/charts/ganache-cli --name=ganache

node -v
npm -v
lerna -v
truffle version

kubectl cluster-info
nsenter --version
minikube addons enable ingress
