#!/bin/bash
TIMESTAMP=$(date +%s)
BUILDID=build-$TIMESTAMP
INSTANCE="travisci/ci-connie:packer-1512502287-986baf0"

docker run \
  --cidfile=.travisci-localtest.cid \
  --name $BUILDID \
  -dit $INSTANCE \
  /sbin/init
