
export const WEB3_CONNECTION_REFUSED = 'WEB3_CONNECTION_REFUSED';
export const WEB3_CONNECTION_SUCCESS = 'WEB3_CONNECTION_SUCCESS';

export const IPFS_CONNECTION_REFUSED = 'IPFS_CONNECTION_REFUSED';
export const IPFS_CONNECTION_SUCCESS = 'IPFS_CONNECTION_SUCCESS';


export const WEB3_ACCOUNTS = 'WEB3_ACCOUNTS';
export const UPDATE_FACTORY_TOUR = 'UPDATE_FACTORY_TOUR';