export const WEB3_CONNECTION_REFUSED = 'WEB3_CONNECTION_REFUSED';
export const WEB3_CONNECTION_SUCCESS = 'WEB3_CONNECTION_SUCCESS';

export const IPFS_CONNECTION_REFUSED = 'IPFS_CONNECTION_REFUSED';
export const IPFS_CONNECTION_SUCCESS = 'IPFS_CONNECTION_SUCCESS';

export const WEB3_ACCOUNTS = 'WEB3_ACCOUNTS';
export const UPDATE_FACTORY_TOUR = 'UPDATE_FACTORY_TOUR';

export const FACTORY_READMODEL_UPDATE = 'FACTORY_READMODEL_UPDATE';

export const EVENTSTORE_READMODEL_UPDATE = 'EVENTSTORE_READMODEL_UPDATE';


export const SAVE_EVENTS = 'SAVE_EVENTS';
