---
- name: helm status ipfs
  shell: "helm status decentralized-storage | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- name: install ipfs
  shell: "helm install $(npm root -g)/transmute-cli/components/ipfs/ --name decentralized-storage --wait"
  when: not output.stdout

- name: ready.w8 decentralized-storage-ipfs
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 decentralized-storage-ipfs default"

# wait a bit longer for ipfs repo lock

- name: minikube_ip
  shell: "minikube ip"
  register: minikube_ip

- name: add ipfs.transmute.minikube to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ minikube_ip.stdout }} ipfs.transmute.minikube'
  become: yes

- name: helm status ganache
  shell: "helm status ganache | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- set_fact:
    ganache_started: "{{ output.stdout }}"

- name: helm status kong
  shell: "helm status gateway | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- set_fact:
    kong_started: "{{ output.stdout }}"
