export const GROUP_LOADED = 'GROUP_LOADED';
export const GROUPS_LOADED = 'GROUPS_LOADED';
export const GROUP_CREATED = 'GROUP_CREATED';
export const GROUP_PROFILE_LOADED = 'GROUP_PROFILE_LOADED';
export const GROUP_DELETED = 'GROUP_DELETED';
export const GROUP_MEMBERS_LOADED = 'GROUP_MEMBERS_LOADED';
export const GROUP_MEMBER_ADDED = 'GROUP_MEMBER_ADDED';
export const GROUP_MEMBER_REMOVED = 'GROUP_MEMBER_REMOVED';
