name: CI
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run coverage
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - name: Generate Private Key
        id: private_key
        uses: ./
        with:
          transmute: |
            jose key generate --alg ES256
      - name: Log Private Key
        run: echo "${{ steps.private_key.outputs.json }}"
