name: CI
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run coverage

  jose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Private Key
        id: generate_private_key
        uses: ./
        with:
          transmute: |
            jose keygen --alg ES256 --verbose
      - name: Log Private Key
        run: echo "${{ steps.generate_private_key.outputs.json }}"
