name: CI
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run coverage

  generate-private-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate_private_key
        uses: ./
        with:
          transmute: |
            jose keygen --alg ES256 --verbose
      - run: echo "${{ steps.generate_private_key.outputs.json }}"
