name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: actions/cache@v3
        with:
          path: |
            ./action.yml
            ./dist
          key: ${{ hashFiles('./dist/**') }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run coverage
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
  generate-private-key:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ./action.yml
            ./dist
          key: ${{ hashFiles('./dist/**') }}
      - id: generate_private_key
        uses: ./
        with:
          transmute: |
            jose keygen --alg ES256 --verbose
      - run: echo "${{ steps.generate_private_key.outputs.json }}"
