name: CI
on: [push]
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ hashFiles('dist/**') }}
          path: >
            action.yml
            dist/*

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run coverage
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
  generate-private-key:
    needs: [cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          key: ${{ hashFiles('dist/**') }}
          path: >
            action.yml
            dist/*

      - id: generate_private_key
        uses: ./
        with:
          transmute: >
            jose keygen --alg ES256 --verbose
      - run: echo "${{ steps.generate_private_key.outputs.json }}"
