name: CI
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run coverage
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          jose: key generate --alg ES256
          private-key: ./private.jwk.json
